### ISSUE TITLE
Traduction du terme "Cron"

### ISSUE THREAD

**Issue by lucalbert** [lalbert/magento2-fr_fr#1]
Module concerné : **Magento_Cron**

Quelle est selon vous la meilleure traduction française du terme "**Cron**" ?
- tâche programmée
- tâche planifiée

**Comment by BKM-Agency** [comment]
mettre "tâche planifiée" mais ne pas enlever le mot Cron car présent sur beaucoup de serveur même français.
Ex ligne 5: Cron (tâches planifiées) - Toutes les heures doivent être convertis en minutes
