### ISSUE TITLE
Magento_Checkout

### ISSUE THREAD

**Issue by lucalbert** [lalbert/magento2-fr_fr#12]
Traduction du module **Magento_Checkout**

![Progress](http://progressed.io/bar/55)
- Nombre total de chaînes : 135
- Nombre de chaînes traduites : 74
- Nombre de chaînes restantes : 61

**Comment by BKM-Agency** [comment]
ok je prend la trad :o)

**Comment by BKM-Agency** [comment]
ok j'ai terminé
