### ISSUE TITLE
Magento_Cms

### ISSUE THREAD

**Issue by lucalbert** [lalbert/magento2-fr_fr#13]
Traduction du module **Magento_Cms**

![Progress](http://progressed.io/bar/74)
- Nombre total de chaînes : 148
- Nombre de chaînes traduites : 110
- Nombre de chaînes restantes : 38

**Comment by BKM-Agency** [comment]
ok je trad !

**Comment by BKM-Agency** [comment]
ok j'ai fini et commité et mergé sur mon espace. j'arrete la pour ce soir ;o)
