### ISSUE TITLE
Magento_ConfigurableProduct

### ISSUE THREAD

**Issue by lucalbert** [lalbert/magento2-fr_fr#15]
Traduction du module **Magento_ConfigurableProduct**

![Progress](http://progressed.io/bar/38)
- Nombre total de chaînes : 124
- Nombre de chaînes traduites : 47
- Nombre de chaînes restantes : 77

**Comment by BKM-Agency** [comment]
a celui là je le prend aussi en trad.

**Comment by BKM-Agency** [comment]
OK terminé, mais GD après vérif n'en fait vriament qu'a ca tête car j'ai du merger sur mon espace!
pourtant le commit était bien sur ta time line :o/ désolé si cela te ralenti, ou bien c GD qui choisi cela si il trouve un problème sur les commits d'avant??? bref je passe sur une autres trad.
