### ISSUE TITLE
Magento_Customer

### ISSUE THREAD

**Issue by lucalbert** [lalbert/magento2-fr_fr#16]
Traduction du module **Magento_Customer**

![Progress](http://progressed.io/bar/62)
- Nombre total de chaînes : 466
- Nombre de chaînes traduites : 291
- Nombre de chaînes restantes : 175

**Comment by BKM-Agency** [comment]
ok je trad celui-ci pour finir la soirée :o)

**Comment by BKM-Agency** [comment]
ok j'ai terminé !
par contre il faudra faire une relecture sur un site en dev afin que tous soit ok car il y a pas mal de changement.

**Comment by lucalbert** [comment]
Oui, on fera une passe avec toutes les traductions lorsqu'on aura tout fini
