### ISSUE TITLE
Traduction du terme "Save"

### ISSUE THREAD

**Issue by lucalbert** [lalbert/magento2-fr_fr#2]
Module concerné : **Global**

Quelle est selon vous la meilleure traduction française du terme "**Save**" ?
- Sauvegarder
- Enregistrer

**Comment by BKM-Agency** [comment]
Il faudait mettre je pense:
"Enregistrer" pour l'action simple (enregistre et retour direct sur la catégorie principale des Produits)
"Sauvegarder ...." pour des actions double (ex. sur création fiche produit le bouton: Sauvegarder et continuer l'édtion)
