### ISSUE TITLE
Magento_Integration

### ISSUE THREAD

**Issue by lucalbert** [lalbert/magento2-fr_fr#21]
Traduction du module **Magento_Integration**

![Progress](http://progressed.io/bar/23)
- Nombre total de chaînes : 109
- Nombre de chaînes traduites : 25
- Nombre de chaînes restantes : 84

**Comment by BKM-Agency** [comment]
ok je prend ca en trad

**Comment by BKM-Agency** [comment]
ok trad terminé pour ce soir. Par contre grosse vérif sur celui-ci car pas mal de nouveauté et anglais lexicalement pauvre, genre 1 mot pour dire a priori 3 choses différente :-1: 
Bref voici la portion a surveiller de la ligne 3751 à 3776
