### ISSUE TITLE
Magento_Authorizenet

### ISSUE THREAD

**Issue by lucalbert** [lalbert/magento2-fr_fr#5]
Traduction du module **Magento_Authorizenet**

![Progress](http://progressed.io/bar/65)
- Nombre total de chaînes : 66
- Nombre de chaînes traduites : 43
- Nombre de chaînes restantes : 23

**Comment by lucalbert** [comment]
![Progress](http://progressed.io/bar/65)

* Nombre total de chaînes : 66
* Nombre de chaînes traduites : 43
* Nombre de chaînes restantes : 23

**Comment by BKM-Agency** [comment]
traduction en cours

**Comment by BKM-Agency** [comment]
ok j'ai terminé !
