### ISSUE TITLE
Magento_Backup

### ISSUE THREAD

**Issue by lucalbert** [lalbert/magento2-fr_fr#6]
Traduction du module **Magento_Backup**

![Progress](http://progressed.io/bar/50)
- Nombre total de chaînes : 78
- Nombre de chaînes traduites : 39
- Nombre de chaînes restantes : 39

**Comment by lucalbert** [comment]
![Progress](http://progressed.io/bar/50)

* Nombre total de chaînes : 78
* Nombre de chaînes traduites : 39
* Nombre de chaînes restantes : 39

**Comment by BKM-Agency** [comment]
ok  je fait la trad
