### ISSUE TITLE
Magento_Braintree

### ISSUE THREAD

**Issue by lucalbert** [lalbert/magento2-fr_fr#7]
Traduction du module **Magento_Braintree**

![Progress](http://progressed.io/bar/44)
- Nombre total de chaînes : 125
- Nombre de chaînes traduites : 55
- Nombre de chaînes restantes : 70

**Comment by lucalbert** [comment]
![Progress](http://progressed.io/bar/44)

* Nombre total de chaînes : 125
* Nombre de chaînes traduites : 55
* Nombre de chaînes restantes : 70

**Comment by BKM-Agency** [comment]
ok je traduit
