### ISSUE TITLE
Problème d'apostrophe

### ISSUE THREAD

**Issue by quienti** [lalbert/magento2-fr_fr#84]
Bonjour,

Tout d'abord, merci pour votre super boulot de traduction de Magento 2 !

Mais, j'ai remarqué un petit soucis, que j'avais déjà remarqué sous Magento 1

> The cache storage may contain additional data. Are you sure that you want to flush it?,Le stockage 
> de cache peut contenir d'autres données. Êtes-vous sûr de vouloir le vider 
> ?,module,Magento_Backend

L'apostrophe de "d'autres" casse le script de Magento, et donc, il empêche l'ouverture de la petite pop-up.

Rien de bien grave, mais ça peut surement régler plusieurs autres soucis

Voilà voilà

**Comment by lucalbert** [comment]
Bonjour @quienti,

Merci pour votre retour.

Nous allons vérifier le problème rapidement.

N'hésitez pas à nous faire remonter d'éventuels autres problèmes rencontrés.

**Comment by lucalbert** [comment]
@quienti,

Pouvez-vous m'indiquer sur quelle(s) page(s) vous avez constaté le problème svp (URL du type "/admin/widget_instance/edit/code/cms_static_block/theme_id/2/").

**Comment by BKM-Agency** [comment]
bonjour a tous, pour infos normalement depuis les version 1.7 les js peuvent échapper les apostrophe.
cependant dans cette version il va falloir vérifier.je pense tout le backend :o|
merci quand même pour les futurs retours a ce sujet quienti :o)

**Comment by quienti** [comment]
@lucalbert 
C'est la gestion du cache, le bouton "Purger le stockage du cache" à cette adresse (admin/admin/cache/index/)

**Comment by lucalbert** [comment]
@quienti, c'est bizarre, j'ai bien l'erreur à certains endroits, mais pas sur cette page.

On est d'accord que c'est le bouton orange "Purger le cache Magento" en haut à droite qui pose problème ?

Est-ce que vous pouvez copier-coller l'erreur de la console s'il y en a une ?

Merci

**Comment by quienti** [comment]
Bien sûr

>  <button id="flush_system" title="Purger le stockage du cache" type="button" class="action-default >  scalable flush-cache-storage" onclick="confirmSetLocation('Le stockage de cache peut contenir 
>  d'autres données. Êtes-vous sûr de vouloir le vider ?', 
> 'http://www.*****.fr/admin/admin/cache/flushAll/key/9eed600e20941977042bdc36a829b42c4d09678
> 7e60201a0b54e24801999b7c2/')"  data-ui-id="adminhtml-cache-container-flush-system-button" >

La ligne de l'erreur dans le html

> Uncaught SyntaxError: missing ) after argument list

Erreur dans la console

Edit : Et c'est le bouton "Purger le stockage du cache", et non le orange

**Comment by lucalbert** [comment]
@quienti,

Je viens de livrer la nouvelle version 0.0.18-alpha qui corrige normalement toutes erreurs dans les scripts.
Cette version ajoute également quelques chaînes non traduites et corrige certaines traductions.
Tu peux maintenant effectuer la mise à jour.

**Comment by quienti** [comment]
D'accord, super !

Je testerai ça sans problème après les fêtes!

Bonne fête de fin d'année à vous
