### ISSUE TITLE
Manque encore des traductions ?

### ISSUE THREAD

**Issue by quienti** [lalbert/magento2-fr_fr#90]
Bonjour,

Pendant divers tests de Magento 2 durant divers développement de module, j'ai remarqué qu'ils manquaient encore certaines traductions.

Ici, lors de l'ouverture du panier sur n'importe quel page
![sans titre 1](https://cloud.githubusercontent.com/assets/7326954/11930771/c815a3b8-a7e6-11e5-9f79-9def1c6c39f3.jpg)
Lorsqu'un article a besoin d'une option personnalisé et que le champ est obligatoire
![sans titre 2](https://cloud.githubusercontent.com/assets/7326954/11930769/c80c796e-a7e6-11e5-8f5f-b7ab1d133c59.jpg)
Encore, lorsque l'on ajout un produit au panier via ajax, et le plus drôle, c'est que "Ajouter au panier" repasse en Anglais après avoir fini
![sans titre 4](https://cloud.githubusercontent.com/assets/7326954/11930770/c80dc5ee-a7e6-11e5-99d0-8f50e4918aa4.jpg)

Après, je ne sais pas si le problème vient de Magento, ou que vous n'avez pas encore terminé, mais je voulais juste pour prévenir

Voilà voilà

**Comment by lucalbert** [comment]
Bonjour @quienti,

Toutes les chaînes ont normalement étaient traduites.
Cependant, j'ai effectivement remarqué qu'il manquait certaines traductions.

Le dictionnaire des traductions a été généré avec la commande [`i18n:collect-phrases`](http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-i18n.html#config-cli-subcommands-xlate-dict) mais il semble que toutes les chaînes ne soient malheureusement pas présentes...

Par contre, de mon coté, certaines chaînes du panier sont bien traduites (4 items => 4 articles; Cart Subtotal => Sous-total du panier; ...)
Avez-vous bien mis à jour le pack de traduction (`composer update`) ?

**Comment by quienti** [comment]
Alors oui, je suis bien à jour
Mais ça dois venir de mes caches ou autres, je regarderai ça plus précisément très prochainement

**Comment by quienti** [comment]
Bonjour,

Alors après avoir complètement supprimer le dossier var/ , tester de remettre la langue du frontend en Anglais puis repasser Français, je n'ai toujours pas toutes les traductions...

Et j'ai bien la dernière version...
Je ne trouve vraiment rien à l'heure actuelle se qui pourrait poser problème...

Je continue de faire des recherches...

**Comment by quienti** [comment]
Oups

**Comment by lucalbert** [comment]
Bon,

Les choses ne sont pas gagnées !
De ce que j'ai vu, la majorité des chaînes non traduites dont tu nous fais part correspondent à des attributs de "binding" et autres valeurs de "template" JavaScript. Exemple [ici](https://github.com/magento/magento2/blob/3b6c4971dc08fee147e91f19a84a275772d79901/app/code/Magento/Checkout/view/frontend/web/template/minicart/content.html#L56).

Je vais poser la question sur le forum de Magento pour comprendre comment ça marche et surtout pourquoi ça ne prend pas en compte les traductions.

---

Pour ton problème de traductions non prises en compte, tu utilises bien composer pour installer les modules ?
Si tu lances la commande `composer show -i lalbert/magento2-fr_fr`, est-ce que tu as bien **\* 0.0.17-alpha*\* pour la version ?

**Comment by quienti** [comment]
![sans titre 6](https://cloud.githubusercontent.com/assets/7326954/11973000/60df88de-a954-11e5-8593-e3113221aed8.jpg)

Oui, installation depuis le composer et je vous confirme bien que j'ai votre dernière version.

Et concernant les traductions `$t('Go to Checkout')`, d'après ce que je sais, c'est un script de traduction, mais je ne sais pas vraiment comment il fonctionne encore, je vais regarder de mon coté.

**Comment by BKM-Agency** [comment]
Bonjour luc, avec les infos de quienti on dirait qu'il lui manque les trad de la partie catalogue.
ou bien c'est peut être dans lib\web\i18n\?

**Comment by quienti** [comment]
![sans titre 4](https://cloud.githubusercontent.com/assets/7326954/11974058/b0a457a8-a960-11e5-8616-a7da30a77f14.jpg)
![sans titre 5](https://cloud.githubusercontent.com/assets/7326954/11974059/b0a8f5ba-a960-11e5-8f89-b84304e0997a.jpg)

Le plus bizarre, c'est que j'ai bien les traductions dans le panier et dans mes produits...
Il n'y a que ce mon mini-panier qui est encore en Anglais...

**Comment by lucalbert** [comment]
Après [renseignements pris](https://github.com/magento/magento2/issues/2793), il semble que ce soit un bug de Magento :(.

Ce qui ne répond pas à la question de savoir comment se fait-il que de mon coté certaines traductions sont ok et pas de ton coté :

![magento2-minicart-fr_fr-1](https://cloud.githubusercontent.com/assets/6500267/11976682/10b3ad28-a97b-11e5-9625-3b0f380066b3.png)

Après, on peut tenter une série de commande pour s'assurer que ça ne vient pas de là :

``` bash
rm -Rf var/cache/* var/di/ var/generation/ var/page_cache/
bin/magento setup:static-content:deploy fr_FR
bin/magento setup:di:compile
bin/magento cache:clean
```

Est-ce que ça persiste (pour "item", "Cart Subtotal" et "Qty") ?

**Comment by quienti** [comment]
Je viens de supprimer complètement mon dossier `pub/static` ainsi que `var/` et j'ai tout régénéré mais rien à faire, j'ai toujours mes textes en Anglais.

Après, est-il possible que le problème vienne parce que j'ai un thème personnalisé ? ( Ça ne se voit pas, mais ce n'est pas le thème Luma par défaut )
De mes différents modules que j'ai créais qui pourrait poser des soucis également ?

**Comment by quienti** [comment]
Ok, euh! J'ai trouvé, enfin, je ne sais pas trop comment ça se fait...

J'ai switch juste pour tests de repasser sur le thème Luma, ça ne fonctionnait toujours pas, donc je suis repassé sur mon thème et là, miracle...

Gné? Je crois que Magento fais ce qu'il veut, quand il veut...

Je ne l'explique pas du tout...

En tout cas, merci pour votre aide !

**Comment by BKM-Agency** [comment]
si c'est le cas d'un thème personnalisé cela fait comme sur la version magento 1.x que tu achète, il faut faire la traduction en ligne ou bien trouver le csv du theme.

**Comment by BKM-Agency** [comment]
ok cela arrive aussi sur les autres versions quand le cache n'est pas actualisé ou bien une persistance du cache navigateur et cookies. Heureux que cela fonctionne bien maintenant pour toi :+1:

**Comment by lucalbert** [comment]
Oui, Magento 2 semble encore avoir quelques secrets à révélés !
Par exemple, il utilise le "Local storage" des navigateurs pour stocker pas mal d'informations dont les traductions : 

![magento2-local-storage](https://cloud.githubusercontent.com/assets/6500267/11981983/ce1ca942-a9a7-11e5-86b9-e54982a5b57a.png)

Plus les quelques bugs dans la matrice qui traînent...

Je pense (j'espère) que les prochaines versions corrigeront un peu ces problèmes qui, pour l'instant, empêchent un peu d'utiliser en prod la version pour le marché français...

En tout cas, cool que ça fonctionne pour toi maintenant !

**Comment by jeromemegel** [comment]
Hello, après avoir pas mal galéré sur un problème de trad voici un tuto qui pourra en aider certains: https://www.megento.fr/blog/probleme-de-traductions-dans-magento-2-les-traductions-ne-fonctionnent-pas

A+
