### ISSUE TITLE
Fautes de frappes

### ISSUE THREAD

**Issue by quienti** [lalbert/magento2-fr_fr#93]
Bonjour,

J'ai trouvé de petite faute de frappe

> We saved the price alert subscription.,Nous avons enregsitré votre abonnement concernant l'alerte de ce prix.,module,Magento_Catalog

et

> You saved the product attribute.,Vous avez enregsitré l'attribut du produit.,module,Magento_Catalog

C'est écrit `enregsitré` au lieu de `enregistré`

Voilà

**Comment by lucalbert** [comment]
Bonjour @quienti,

Merci.
C'est corrigé et sera disponible dans une prochaine livraison.
