### ISSUE TITLE
Magento 2.0.2 ?

### ISSUE THREAD

**Issue by quienti** [lalbert/magento2-fr_fr#94]
Bonjour,

Est ce que votre version est toujours à jour avec la version Magento 2.0.2 ?
Il m'a semblé voir qu'ils avaient corrigés des problèmes lié aux traductions

Merci d'avance

**Comment by lucalbert** [comment]
Bonjour,

Nous n'avons pas encore fait de mise à jour concernant cette nouvelle version, mais nous allons nous y pencher dessus.

**Comment by quienti** [comment]
Bonjour,

Merci de votre réponse, si vous avez besoin d'aide, vous pouvez me contacter !

**Comment by lucalbert** [comment]
Bonjour @quienti,

Je viens de livrer la version 1.0.0 qui prend en compte les nouvelles traductions de la version 2.0.2.

Il reste toujours des bugs d'échappements et des traductions manquantes qui sont prises en compte dans le package.

**Comment by quienti** [comment]
Bonjour,

Oui, j'ai vue les notifications.

Merci beaucoup
