### ISSUE TITLE
Traduction de ANY pour les règles de prix. 

### ISSUE THREAD

**Issue by NetAssoPro** [lalbert/magento2-fr_fr#99]
Ligne 3387 il faut remplacer ANY par "Au moins une" sinon à l'affichage de la liste de sélection des critère, on a juste le droit entre "Tous" et "Tous" (All et Any).

**Comment by lucalbert** [comment]
Bonjour @NetAssoPro,

Merci pour le partage.

Je viens de livrer la version 1.0.1 qui corrige le problème.

Vous pouvez faire la mise à jour pour prendre en compte la nouvelle version :

```
$ composer update lalbert/magento2-fr_fr
$ bin/magento cache:clean
```

**Comment by NetAssoPro** [comment]
Merci à vous pour la ressource !

Maxime DANJOU

De : Luc ALBERT [mailto:notifications@github.com]
Envoyé : mercredi 25 mai 2016 11:32
À : lalbert/magento2-fr_fr
Cc : Support; Mention
Objet : Re: [lalbert/magento2-fr_fr] Traduction de ANY pour les règles de prix. (#99)

Bonjour @NetAssoProhttps://github.com/NetAssoPro,

Merci pour le partage.

Je viens de livrer la version 1.0.1 qui corrige le problème.

Vous pouvez faire la mise à jour pour prendre en compte la nouvelle version :

$ composer update lalbert/magento2-fr_fr

$ bin/magento cache:clean
